version: "3.9"
services:
  web:
    build: .
    ports:
      - "5001:5001"
  redis:
    image: "redis:alpine"

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: api
      POSTGRES_PASSWORD: chatapp
      POSTGRES_USER: nipa
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "127.0.0.1:5433:5433"